Fix cyclic import in Chromecast Provider (#2296)
#2249 introduced a cyclic import resulting in an `ImportError: cannot import name 'ChromecastProvider' from partially initialized module` on launch.

There are still many `Cyclic detected in import chain` errors reported by pyright, but at least they are not causing runtime issues due to being in `TYPE_CHECKING` blocks.